{% set name = "google-cloud-recommender" %}
{% set version = "2.15.5" %}
{% set sha256 = "12d87b14ba58a20f5c1cf8b40bc6540ca968d059e50753d7c61f035a009ddcae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.10.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.recommender
    - google.cloud.recommender_v1

about:
  home: https://github.com/googleapis/python-recommender
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Recommender API client library
  description: "Google Cloud Recommender API is a Google Cloud service that provides recommendations for cloud customers for various categories like performance optimization, cost savings, reliability, feature discovery, etc. These recommendations are generated automatically based on analysis of user resources, configuration
    and monitoring metrics.\nSee the [quick start guide](https://googleapis.dev/python/recommender/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/recommender/latest/index.html
  dev_url: https://github.com/googleapis/python-recommender

extra:
  recipe-maintainers:
    - parthea
